# Ag Ibragimov
[agzam.ibragimov@gmail.com](mail-to:agzam.ibragimov@gmail.com)
[Walnut Creek, CA](https://goo.gl/maps/1RrnrxnpFFH2)
[Stackoverflow](http://stackoverflow.com/users/116395/agzam)
[LinkedIn](https://www.linkedin.com/in/agzam)
[github](https://github.com/agzam)

## About me:

&nbsp;&nbsp;I am a software developer working on front-end (web) side of things for the past few years. Mostly I have been developing proprietary products. To my regret my full-time job leaves me very little time to participate in open-source projects.

&nbsp;&nbsp;I am quite gainfully employed right now, however I am always curios about new things.

&nbsp;&nbsp;I like teams aimed to deliver awesome products, driven by those who are not afraid to use cutting-edge platforms, tools and standards, to work with people who understand importance of automated testing and strive for perfection in the code and in the final product.

&nbsp;&nbsp;My preference lies in considering full-time, permanent positions, where I could participate in building modern web/hybrid apps backed by Clojurescript/Clojure and/or Node.js. Recently I fell in love with Clojure and I would like to extend my exposure into that amazing language. Also I would be interested in exploring other languages with strong functional emphasis like Elm, Purescript, Scala or Haskell.

#### For various reasons, currently I am NOT very excited about:

* .net C# based projects. *Although I have done it before and still love C#, when given no choice but to build .net compatible solution, I would probably try to use F# or Clojure*
* projects heavily based on Java, Python (Django/Flask etc.) or Ruby (Rails, Sinatra, etc.). *Let me clarify - I am fine with maintaining legacy code, however If asked to start a brand new project based on an imperative language, I would probably try to convince stakeholders otherwise*

#### What do I do:
* I am capable of making interactive, responsive and adaptive web apps, scalable, enterprise level solutions with complex UI and logic, mobile apps and cloud based services
* Fanatic of automated testing, decoupling code fractions, creating reusable components and when needed - microservices
* I prefer functional programming constructs, I love reactive programming, at the same time I understand OOP principles and apply them when that makes sense
* Constantly trying to find ways to improve my productivity, I consider time spent on learning Vim, Emacs and plethora of other tools is my best lifetime investment
* I have done stuff and played with following languages: JavaScript, Coffeescript, Typescript, Livescript, Clojure, C#, Python. I am Familiar with Ruby, Java and Elisp

## Professional experience

### [Mobitor](http://www.mobitor.com)
`Lead Front-end Developer` `Apr 2015-current` `Walnut Creek, CA`

##### Responsibilities:
Suite for managing medical devices (orthopedic, spine surgery equipment and implants)

###### Components
babel.js, coffeescript, node, couchbase, rxjs, angular, karma, protractor, gulp, postcss

### [Invitae](https://www.invitae.com)
`Lead Front-end Developer and Architect` `May 2014-Apr 2015` `San Francisco, CA`

##### Responsibilities:
Building asset tracking/dashboard web app

###### Components
coffeescript, python, node, rxjs, angular, karma, protractor, gulp, d3, browserify, stylus, jade, elasticsearch

### [VEVO](http://www.vevo.com)
`Senior Software Developer` `Jan 2012-May 2014` `New York and San Francisco`

##### Responsibilities:
* Implemented cloud-based, task-driven, scalable, 10x more efficient (than the old one) video encoding system
* Lead a group of developers on a web project - product that has been used internally by staff and by partners
* Google Chromecast integration with Vevo apps - in Chrome browser, on iOS and Android
* Apple TV App
* Participated in redesigning vevo.com from scratch, switching from asp.net mvc to node/angular

###### Components
javascript, coffeescript, c#, node, asp.net, angular, AWS

### [Bunk1.com](https://www.bunk1.com)
`Front-end Developer` `2011` `461 Park Avenue South, New York`

##### Responsibilities:
* Web apps and various widgets (e.g. calendar)
* iPhone and iPad apps using Xamarin tools

###### Components
c#, javascript, asp.net, backbone, jquery, objective-c, mono touch, xamarin tools

### [USeDirect](https://www.usedirect.com)
`Application Developer` `2010` `Roslyn Heights, NY`

##### Responsibilities:
Desktop UI shell to manage custom Microsoft Dynamics solution

###### Components
c#, WPF

### Focus Solutions
`Application Developer` `2010` `Melville, NY`

##### Responsibilities:
Software suite for military facilities, for reliably and safely identify, track and maintain arms, ammunition and explosives using automatic identification technology based on RFID tracking

###### Components
c#, WPF, entity framework

### Freelance Programmer
`2009` `New York City, NY`

##### Responsibilities:
* High-frequency trading app for Dimension Capital LLC
    * Building fast, highly responsive, secured decision-making tool for automated stock trading based on monitored accounts of other stockbrokers.
* QA automation for RI Communications group
* Web projects for Exotag

###### Components
c#, javascript, wordpress, php

### [Educational Services & Products](http://www.esp-sgs.com)
`Web Developer` `2008-2009` `Brooklyn, NY`

asp.net web apps

### CodeLuxe
`Application Developer` `2008` `Moscow, Russia`

Developing casual games based on Silverlight

### DENISE Fashion Stores
`Chief Information Officer` `2007-2008` `Moscow, Russia`

Maintaining ERP, Sales and Retail management systems

### [PlusSoft](http://plussoft.uz) 
`Senior Software Developer` `2003-2006` `Tashkent, Uzbekistan`
* Ticket booking software suite for Uzbekistan Airways
* Project for National broadcasting company for planning, allocation and monitoring TV commercials

### A&A Software
`Senior Software Developer` `2005-2006` `Dubai, UAE`

Commissioned as a consultant by "PlusSoft"

##### Responsibilities:
* Bookkeeping software for air-cargo companies ("[Aerovista](http://www.aerovista.aero)" and "[RusAviation](http://www.rusaviation.com)")
* Car renting suite for rent-a-car facilities in Dubai

### Spektr
`System Administrator` `2001-2003` `Pyatigorsk, Russia`

ERP suite. Staff and salary modules

### [National Broadcasting Company](http://www.mtrk.uz/en)
`Web Designer` `1999-2001` `Tashkent, Uzbekistan`

  &nbsp;

### [State Tax Committee](https:\\soliq.uz)
`Support Specialist` `1996-1999` `Tashkent, Uzbekistan`

## Education

#### [Tashkent City College of Information Technologies](kalanovo.uz)
 Bachelor of Science in Information Technology &nbsp; `1992-1996`

&nbsp; &nbsp;
 updated: December 2015
