# Ag Ibragimov
[agzam.ibragimov@gmail.com](mail-to:agzam.ibragimov@gmail.com)
[Walnut Creek, CA](https://goo.gl/maps/1RrnrxnpFFH2)
[Stackoverflow](http://stackoverflow.com/users/116395/agzam)
[LinkedIn](https://www.linkedin.com/in/agzam)
[github](https://github.com/agzam)

## About me:

* For the past few years mostly I've been working on front-end (web) side of things, developing proprietary products. Sadly, full-time job leaves me very little time for open-source projects.
* I am looking for a role where I would be creating modern web/hybrid apps backed by Clojurescript/Clojure or Node.js. Recently I fell in love with Clojure and I would like to extend my exposure into this amazing language. I might be also interested in exploring other languages with strong functional emphasis, e.g: Elm, Haskell, Purescript or Scala.
* I am capable of building interactive, responsive and adaptive web sites, scalable enterprise level solutions with complex UI and logic, mobile apps, cloud services and APIs
* Fanatic of automated testing, I often choose reusable components and microservices instead of creating monolithic structures
* I prefer functional programming constructs, I love reactive programming. I understand OOP principles as well, and apply them when see fit
* I constantly try to improve my productivity. Time spent on learning Vim, Emacs and plethora of other tools is my best investment
* I've attained proficiency in: JavaScript, Coffeescript, Typescript, Livescript, Clojure, C#, Python. I am Familiar with Ruby, Java and Emacs Lisp

## Professional experience

### [Mobitor](http://www.mobitor.com)
`Lead Front-end Developer` `since Apr 2015` `Walnut Creek, CA`

##### Responsibilities:
Suite for managing medical devices - orthopedic, spine surgery implants and equipment

###### Components
babel.js, coffeescript, node, couchbase, rxjs, angular, karma, protractor, gulp, postcss, docker

### [Invitae](https://www.invitae.com)
`Lead Front-end Developer and Architect` `May 2014 - Apr 2015` `San Francisco`

##### Responsibilities:
Building asset tracking/dashboard web app

###### Components
coffeescript, python, node, rxjs, ramda.js, angular, karma, protractor, gulp, d3, browserify, stylus, jade, elasticsearch

### [VEVO](http://www.vevo.com)
`Senior Software Developer` `Jan 2012 - May 2014` `New York/San Francisco`

##### Responsibilities:
* Implemented cloud-based, task-driven, scalable, efficient video encoding system
* Lead a group of developers in building a web-site that's being used by company staff and partners
* Google Chromecast integration for Vevo apps
* Apple TV App
* Participated in redesigning vevo.com, switching from ASP.net MVC to node.js/angular

###### Components
javascript, coffeescript, c#, node, ASP.net, angular, AWS

### [Bunk1.com](https://www.bunk1.com)
`Front-end Developer` `2011` `New York`

##### Responsibilities:
* Web and mobile apps

###### Components
c#, javascript, asp.net, backbone, jquery, objective-c, mono touch, xamarin tools

### [USeDirect](https://www.usedirect.com)
`Application Developer` `2010` `Roslyn Heights, NY`

##### Responsibilities:
Microsoft Dynamics desktop UI shell

###### Components
c#, WPF

### Focus Solutions
`Application Developer` `2010` `Melville, NY`

##### Responsibilities:
Software suite for military facilities, for reliably and safely identify, track and maintain arms, ammunition and explosives using RFID tracking

###### Components
c#, WPF, entity framework

### Freelance Programmer
`-` `2009` `New York`

##### Responsibilities:
* High-frequency trading app for Dimension Capital - fast, responsive, secure automated decision-making tool for trading
* QA automation for RI Communications Group
* Web projects for Exotag

###### Components
c#, javascript, wordpress, php

### [Educational Services & Products](http://www.esp-sgs.com)
`Web Developer` `2008 - 2009` `Brooklyn, NY`

Medicaid reimbursement web-site for school districts 

### CodeLuxe
`Application Developer` `2008` `Moscow, Russia`

Casual video games

### DENISE Fashion Stores
`Chief Information Officer` `2007 - 2008` `Moscow, Russia`

Responsible for ERP, Sales and Retail management systems

### [PlusSoft](http://plussoft.uz) 
`Senior Software Developer` `2003 - 2006` `Tashkent, Uzbekistan`
* Ticket booking suite for Uzbekistan Airways
* Project for National Broadcasting Company - for planning, allocating and monitoring ads

### A&A Software
`Senior Software Developer` `2005 - 2006` `Dubai, UAE`

##### Responsibilities:
* Accounting solutions for air-cargo companies ("[Aerovista](http://www.aerovista.aero)" and "[RusAviation](http://www.rusaviation.com)")
* Car rental automation suite

### Spektr
`System Administrator` `2001 - 2003` `Pyatigorsk, Russia`

Maintaining ERP system. Staff and salary modules

## Education

#### [Tashkent City College of Information Technologies](kalanovo.uz)
 Bachelor of Science in Information Technology &nbsp; `1992 - 1996`

&nbsp; &nbsp;
 updated: December 2015
