# Ag Ibragimov
[agzam.ibragimov@gmail.com](mail-to:agzam.ibragimov@gmail.com)
[Walnut Creek, CA](https://goo.gl/maps/1RrnrxnpFFH2)
[Stackoverflow](http://stackoverflow.com/users/116395/agzam)
[LinkedIn](https://www.linkedin.com/in/agzam)
[github](https://github.com/agzam)

## About me:

* For the past few years I have been working on front-end (web) side of things. Mostly developing proprietary products. Sadly, my full-time job leaves me very little time for open-source projects.
* My preference lies in considering full-time, long-term positions where I could participate in building modern web/hybrid apps backed by Clojurescript/Clojure and/or Node.js. Recently I fell in love with Clojure and I would like to extend my exposure into that amazing language. I might be also interested in exploring other languages with strong functional emphasis like Elm, Haskell, Purescript or Scala.
* I am capable of creating interactive, responsive and adaptive web sites, scalable enterprise level solutions with complex UI and logic, mobile apps and cloud based services
* fanatic of automated testing, I often choose reusable components and microservices instead of creating monolithic structures
* I prefer functional programming constructs, I love reactive programming. I understand OOP principles as well, and apply them when see fit
* I constantly try to improve my productivity. Time spent on learning Vim, Emacs and plethora of other tools is my best investment
* I attained proficiency in: JavaScript, Coffeescript, Typescript, Livescript, Clojure, C#, Python. I am Familiar with Ruby, Java and Elisp

#### For various reasons, currently I am NOT very excited about:

* .net based projects. *Although I have done it before and still love C#, if given no choice but to build .net compatible solution, probably will try to use F# or Clojure*
* projects heavily dependent on Java, Python or Ruby (GWT, Django, Flask, Rails, Sinatra, etc.) *I am fine with maintaining legacy code, however If asked to start a brand new project based on an imperative language, probably will try to convince stakeholders otherwise*


## Professional experience

### [Mobitor](http://www.mobitor.com)
`Lead Front-end Developer` `since Apr 2015` `Walnut Creek, CA`

##### Responsibilities:
Suite for managing medical devices - orthopedic, spine surgery implants and equipment and implants

###### Components
babel.js, coffeescript, node, couchbase, rxjs, angular, karma, protractor, gulp, postcss, docker

### [Invitae](https://www.invitae.com)
`Lead Front-end Developer and Architect` `May 2014 - Apr 2015` `San Francisco`

##### Responsibilities:
Building asset tracking/dashboard web app

###### Components
coffeescript, python, node, rxjs, ramda.js, angular, karma, protractor, gulp, d3, browserify, stylus, jade, elasticsearch

### [VEVO](http://www.vevo.com)
`Senior Software Developer` `Jan 2012 - May 2014` `New York/San Francisco`

##### Responsibilities:
* implemented cloud-based, task-driven, scalable, efficient video encoding system
* lead a group of developers in building a web-site that's being used by company staff and partners
* Google Chromecast integration with Vevo apps
* Apple TV App
* participated in redesigning vevo.com, switching from ASP.net MVC to node.js/angular

###### Components
javascript, coffeescript, c#, node, ASP.net, angular, AWS

### [Bunk1.com](https://www.bunk1.com)
`Front-end Developer` `2011` `New York`

##### Responsibilities:
* Web and mobile apps

###### Components
c#, javascript, asp.net, backbone, jquery, objective-c, mono touch, xamarin tools

### [USeDirect](https://www.usedirect.com)
`Application Developer` `2010` `Roslyn Heights, NY`

##### Responsibilities:
Desktop UI shell for custom Microsoft Dynamics solution

###### Components
c#, WPF

### Focus Solutions
`Application Developer` `2010` `Melville, NY`

##### Responsibilities:
Software suite for military facilities, for reliably and safely identify, track and maintain arms, ammunition and explosives using RFID tracking

###### Components
c#, WPF, entity framework

### Freelance Programmer
`-` `2009` `New York`

##### Responsibilities:
* High-frequency trading app for Dimension Capital LLC
    * Building fast, responsive, secured decision-making tool for automated trading
* QA automation for RI Communications group
* Web projects for Exotag

###### Components
c#, javascript, wordpress, php

### [Educational Services & Products](http://www.esp-sgs.com)
`Web Developer` `2008 - 2009` `Brooklyn, NY`

ASP.net web apps

### CodeLuxe
`Application Developer` `2008` `Moscow, Russia`

casual video games

### DENISE Fashion Stores
`Chief Information Officer` `2007 - 2008` `Moscow, Russia`

Maintaining ERP, Sales and Retail management systems

### [PlusSoft](http://plussoft.uz) 
`Senior Software Developer` `2003 - 2006` `Tashkent, Uzbekistan`
* Ticket booking software suite for Uzbekistan Airways
* Project for National broadcasting company for planning, allocation and monitoring TV commercials

### A&A Software
`Senior Software Developer` `2005 - 2006` `Dubai, UAE`

Commissioned by "PlusSoft" for consulting

##### Responsibilities:
* Bookkeeping software for air-cargo companies ("[Aerovista](http://www.aerovista.aero)" and "[RusAviation](http://www.rusaviation.com)")
* Car renting suite for rent-a-car facilities in Dubai

### Spektr
`System Administrator` `2001 - 2003` `Pyatigorsk, Russia`

ERP suite. Staff and salary modules

### [National Broadcasting Company](http://www.mtrk.uz/en)
`Video engineer` `1999 - 2001` `Tashkent, Uzbekistan`

  &nbsp;

### [State Tax Committee](https:\\soliq.uz)
`Support Specialist` `1996 - 1999` `Tashkent, Uzbekistan`

## Education

#### [Tashkent City College of Information Technologies](kalanovo.uz)
 Bachelor of Science in Information Technology &nbsp; `1992 - 1996`

&nbsp; &nbsp;
 updated: December 2015
